name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # We want to run all the versions to see if a failure is version specific
      matrix:
        ghidra:
#          - "latest"
          - "11.4"
#          - "11.3.2"
#          - "11.2.1"
          # - "11.1.1"
          # - "11.1"
          # - "11.0.3"
          # - "11.0.2"
          # - "11.0.1"
          # - "11.0"

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
  
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Install Ghidra ${{ matrix.ghidra }}
      uses: antoniovazquezblanco/setup-ghidra@v2.0.4
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra }}

    - name: Build
      run: gradle classes

    - name: Run tests (with Xvfb)
      uses: coactions/setup-xvfb@v1
      with:
        run: gradle test --info
