name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghidra:
#          - "latest"
          - "11.3"
          - "11.2.1"
          # - "11.1.1"
          # - "11.1"
          # - "11.0.3"
          # - "11.0.2"
          # - "11.0.1"
          # - "11.0"

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
  
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Install Ghidra ${{ matrix.ghidra }}
      uses: antoniovazquezblanco/setup-ghidra@v2.0.4
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra }}

    - name: Linting with klint
      run: gradle ktlintCheck

    - name: Test
      run: gradle test

    - name: Build
      run: gradle buildExtension

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Apple_Ghidra_${{ matrix.ghidra }}
        path: dist/*.zip
